-- Создание таблицы предметов
CREATE TABLE IF NOT EXISTS t_subject (
                                         subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         t_name VARCHAR(255) NOT NULL,
                                         t_teacher VARCHAR(255) NOT NULL,
                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы студентов
CREATE TABLE IF NOT EXISTS t_student (
                                         student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         t_name VARCHAR(255) NOT NULL,
                                         t_lastname VARCHAR(255) NOT NULL,
                                         t_email VARCHAR(255) UNIQUE NOT NULL,
                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы промежуточных результатов (финалы/экзамены)
CREATE TABLE IF NOT EXISTS t_finals (
                                        final_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        t_name VARCHAR(255) NOT NULL,
                                        t_date DATE NOT NULL,
                                        student_id BIGINT NOT NULL,
                                        subject_id BIGINT NOT NULL,
                                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                        CONSTRAINT fk_finals_student
                                            FOREIGN KEY (student_id)
                                                REFERENCES t_student(student_id)
                                                ON DELETE CASCADE,

                                        CONSTRAINT fk_finals_subject
                                            FOREIGN KEY (subject_id)
                                                REFERENCES t_subject(subject_id)
                                                ON DELETE CASCADE
);

-- Создание таблицы связи многие-ко-многим между студентами и предметами
CREATE TABLE IF NOT EXISTS student_subject (
                                               student_id BIGINT NOT NULL,
                                               subject_id BIGINT NOT NULL,
                                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                               PRIMARY KEY (student_id, subject_id),

                                               CONSTRAINT fk_student_subject_student
                                                   FOREIGN KEY (student_id)
                                                       REFERENCES t_student(student_id)
                                                       ON DELETE CASCADE,

                                               CONSTRAINT fk_student_subject_subject
                                                   FOREIGN KEY (subject_id)
                                                       REFERENCES t_subject(subject_id)
                                                       ON DELETE CASCADE
);

-- Создание индексов для оптимизации запросов
CREATE INDEX idx_student_email ON t_student(t_email);
CREATE INDEX idx_finals_student ON t_finals(student_id);
CREATE INDEX idx_finals_subject ON t_finals(subject_id);
CREATE INDEX idx_finals_date ON t_finals(t_date);
CREATE INDEX idx_student_subject_student ON student_subject(student_id);
CREATE INDEX idx_student_subject_subject ON student_subject(subject_id);

-- Комментарии к таблицам
COMMENT ON TABLE t_subject IS 'Таблица предметов/дисциплин';
COMMENT ON TABLE t_student IS 'Таблица студентов';
COMMENT ON TABLE t_finals IS 'Таблица финальных работ/экзаменов';
COMMENT ON TABLE student_subject IS 'Таблица связи студентов и предметов (многие-ко-многим)';