
CREATE TABLE IF NOT EXISTS t_permission (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            name VARCHAR(100) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS t_user (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      username VARCHAR(255),
                                      email VARCHAR(255) NOT NULL UNIQUE,
                                      password VARCHAR(255) NOT NULL,
                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS t_user_permissions (
                                                  user_id BIGINT NOT NULL,
                                                  permissions_id BIGINT NOT NULL,

                                                  PRIMARY KEY (user_id, permissions_id),

                                                  CONSTRAINT fk_user_permissions_user
                                                      FOREIGN KEY (user_id)
                                                          REFERENCES t_user(id)
                                                          ON DELETE CASCADE,

                                                  CONSTRAINT fk_user_permissions_permission
                                                      FOREIGN KEY (permissions_id)
                                                          REFERENCES t_permission(id)
                                                          ON DELETE CASCADE
);


CREATE INDEX idx_user_email ON t_user(email);
CREATE INDEX idx_user_permissions_user ON t_user_permissions(user_id);
CREATE INDEX idx_user_permissions_permission ON t_user_permissions(permissions_id);


COMMENT ON TABLE t_user IS 'Таблица пользователей системы';
COMMENT ON TABLE t_permission IS 'Таблица прав доступа';
COMMENT ON TABLE t_user_permissions IS 'Связь пользователей и прав (many-to-many)';
